# Generated by Django 2.2 on 2019-04-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='url',
        ),
    ]
