# Generated by Django 2.2 on 2019-04-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190402_1639'),
        ('core', '0005_question_liked_by'),
        ('core', '0005_auto_20190403_0800'),
    ]

    operations = [
    ]
