# Generated by Django 2.2 on 2019-04-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190403_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='starred_at',
        ),
        migrations.AddField(
            model_name='answer',
            name='starred_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
